(BNAPP-1714)handle username if so long
OpusCapita/service-base-ui pull request #125
Opened 2022-06-23 10:15 UTC by KrystianKasp98

# Description

Fixes [BNAPP-1714](https://opuscapita.atlassian.net/browse/BNAPP-1714).

<ins>Please include a summary of the change (current and new behavior):</ins>

Shortcut for too long username.

<br/>

### 🛠️ Type of change

Please check the type of change your PR introduces:
- [ ] Feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

<br/>

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

<br/>

# How to test the change locally
Just log in as user with long username E.g. `manager.commodity_de@acmemax.com`, then open user window and check results

*✍️ replace this line ✍️*

<br/>

# Other informations

2022-06-23 11:24 UTC, ElaCzapiewska requested changes
Please rethink the solution as I am not convinced. 
1. if you display anything like xyz... you should also give the possibility to view the whole string (on hoover or whatever)
2. this can also be last name that can be too long
3. this 25 chars limit and the approach used would completely destroy mine window which is very nice currently having very long data (probably the "-" helps here, but anyway...)
![Screenshot from 2022-06-23 13-15-26](https://user-images.githubusercontent.com/70636925/175287412-57e67e6a-3fe7-4dee-ab11-f4822e130857.png)

2022-06-28 06:06 UTC, KacperKlosowskiOC requested changes
Nice :) Tiny remarks only.

2022-06-28 07:04 UTC, ElaCzapiewska requested changes
Nice, only tiny formatting remarks

2022-06-28 07:04 UTC, ElaCzapiewska commented on components/MainMenu/MainMenu.react.js
> +        this.context.showNotification(this.context.i18n.getMessage('Main.notification.copyToClipBoard',{userName}), 'info', 3);
please put a space before each next argument of a function call

2022-06-28 07:04 UTC, ElaCzapiewska commented on components/MainMenu/Menu/components/MenuAccount/MenuAccount.react.js
> +                        <div className="user-name" title={userName} onClick={()=>copyTextToClipBoard(userName)}>{this.prepareUserName(userName)}</div>
please put spaces in arrow function definition

2022-06-28 08:07 UTC, KacperKlosowskiOC approved these changes
:rocket:

2022-06-29 05:33 UTC, merged