feature/GENESIS-306-default-lang-selection-english
OpusCapita/service-base-ui pull request #92
Opened 2021-01-18 14:44 UTC by ElaCzapiewska

if user.UserProfile.languageId is not supported in the UI the default
selected value of upper right corner UI component is EN

2021-01-18 14:57 UTC, jaconsta requested changes
Nice!!! I left one comment.

Nice-to-have. To reduce the file size, would be nice to have the language selection on it's own component. What do you think?

2021-01-18 14:57 UTC, jaconsta commented on components/MainMenu/MainMenu.react.js
> +        return Object.keys(supportedLanguages).map((lang, id) => <option key={id} value={lang}>{supportedLanguages[lang]}</option>);
is Id a number representing the position of the language in the array? If so, it's better to use the `lang` attribute as `key`

https://reactjs.org/docs/lists-and-keys.html#keys

2021-01-18 14:57 UTC, jaconsta commented
Remember to update the branch with master.

2021-01-18 18:51 UTC, ElaCzapiewska commented on components/MainMenu/MainMenu.react.js
> +        return Object.keys(supportedLanguages).map((lang, id) => <option key={id} value={lang}>{supportedLanguages[lang]}</option>);
ok changed, key={lang}

2021-01-18 19:05 UTC, ElaCzapiewska commented
ok, I moved language selection on it's own component.
this branch is derived from master.

2021-01-19 15:21 UTC, jaconsta requested changes
Small adjustment, please.

2021-01-19 15:21 UTC, jaconsta commented on components/MainMenu/Menu/components/MenuSelectLanguage/MenuSelectLanguage.react.js
> +import Types from 'prop-types';
Can you please use PropTypes instead, just to follow the standart way

2021-01-19 16:28 UTC, ElaCzapiewska commented on components/MainMenu/Menu/components/MenuSelectLanguage/MenuSelectLanguage.react.js
> +import Types from 'prop-types';
ok, done

2021-01-19 17:21 UTC, jaconsta approved these changes
:rocket: LGTM.

2021-01-20 08:02 UTC, merged